version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

