name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script; skipping"
          fi

      - name: Run tests
        run: |
          if npm run | grep -q "test"; then
            npm test -- --ci --reporters=default
          else
            echo "No test script; skipping"
          fi

      - name: Build
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script; skipping"
          fi

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            **/junit.xml
            **/coverage/**
          if-no-files-found: ignore

