name: Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm ci

      - name: ESLint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script; skipping"
          fi

  codeql:
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: github/codeql-action/.github/workflows/codeql.yml@v3
    with:
      languages: javascript

