name: Release Notes

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers when version tags like v1.0.0, v1.1.0 are pushed
  workflow_dispatch:  # Allows manual run too

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      releases: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = process.env.GITHUB_REF.replace('refs/tags/', '');
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 20
            });

            const lines = commits.map(c => `- ${c.commit.message.split('\n')[0]} (${c.sha.substring(0,7)})`);
            const body = `## Changes in ${tag}\n\n` + lines.join('\n');

            core.setOutput('body', body);
            core.setOutput('tag', tag);

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.notes.outputs.tag }}
          name: Release ${{ steps.notes.outputs.tag }}
          body: ${{ steps.notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm release created
        run: echo "✅ Release successfully created for ${{ steps.notes.outputs.tag }}"
